package ControllerForm;

import Dto.CustomerDto;
import Model.CustomerModel;
import Tm.CustomerTm;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class CustomerForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerForm.class.getName());

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCusId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtConNum = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbUserId = new javax.swing.JComboBox<>();
        CustomerSaveBtn = new javax.swing.JButton();
        CustomerUpdateBtn = new javax.swing.JButton();
        CustomerDeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Customer Form");

        jLabel1.setText(" ID");

        jLabel2.setText("Name");

        jLabel4.setText("Contact Number");

        jLabel5.setText("Email");

        jLabel6.setText("User ID");

        cmbUserId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserIdActionPerformed(evt);
            }
        });

        CustomerSaveBtn.setText("Save");
        CustomerSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerSaveBtnActionPerformed(evt);
            }
        });

        CustomerUpdateBtn.setText("Update");
        CustomerUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerUpdateBtnActionPerformed(evt);
            }
        });

        CustomerDeleteBtn.setText("Delete");
        CustomerDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDeleteBtnActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer ID", "Name", "Contact Number", "UserId", "Email"
            }
        ));
        jScrollPane1.setViewportView(tblCustomer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCusId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtConNum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(CustomerSaveBtn)
                        .addGap(60, 60, 60)
                        .addComponent(CustomerUpdateBtn)
                        .addGap(60, 60, 60)
                        .addComponent(CustomerDeleteBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtConNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerSaveBtn)
                            .addComponent(CustomerUpdateBtn)
                            .addComponent(CustomerDeleteBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(545, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void initialize() {
        generateCustomerId();
        populateComboBox();
        loadAllCustomer();
        //populateComboBoxEmpType();
    }

    private void CustomerSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerSaveBtnActionPerformed
        // TODO add your handling code here:
        CustomerModel model = new CustomerModel();
        String id = txtCusId.getText();
        String name = txtName.getText();
        String conNum = txtConNum.getText();
        String email = txtEmail.getText();
        int userId = Integer.parseInt(cmbUserId.getSelectedItem().toString());

        var dto = new CustomerDto(id, name, conNum, userId, email);

        boolean flag = false;
        try {
            flag = model.save(dto);
        } catch (SQLException ex) {
            System.getLogger(CustomerForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        if (flag) {
            JOptionPane.showMessageDialog(this,
                    "Customer saved successfully! ",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Failed to save customer.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CustomerSaveBtnActionPerformed

    private void cmbUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserIdActionPerformed

    private void CustomerUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerUpdateBtnActionPerformed
        // TODO add your handling code here:
       java.awt.EventQueue.invokeLater(() -> {
        try {
            CustomerUpdateForm form = new CustomerUpdateForm();
            form.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            form.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Failed to open Customer Update Form: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    });
    }//GEN-LAST:event_CustomerUpdateBtnActionPerformed

    private void CustomerDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDeleteBtnActionPerformed
        // TODO add your handling code here:
       java.awt.EventQueue.invokeLater(() -> {
        try {
            CustomerDeleteForm form = new CustomerDeleteForm();
            form.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
            form.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Failed to open Customer Delete Form: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    });
    }//GEN-LAST:event_CustomerDeleteBtnActionPerformed

    public void populateComboBox() {

        try {
            List<String> dataFromDB = CustomerModel.getCmbUserId();

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

            for (String item : dataFromDB) {
                model.addElement(item);
            }

            cmbUserId.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private String generateCustomerId() {
        String cusId = null;
        try {
            cusId = CustomerModel.getGenerateEmployeeId();
            txtCusId.setText(cusId);
        } catch (SQLException e) {
            // new Alert(Alert.AlertType.ERROR, e.getMessage()).show();
        }

        return cusId;
    }

    public void loadAllCustomer() {
        var model = new CustomerModel();

        try {
            List<CustomerDto> dtoList = model.getAll();

            // Get the table model from your JTable
            DefaultTableModel tableModel = (DefaultTableModel) tblCustomer.getModel();

            // Clear existing rows
            tableModel.setRowCount(0);

            // Add rows to the table
            for (CustomerDto dto : dtoList) {
                Object[] rowData = {
                    dto.getCusId(),
                    dto.getCusName(),
                    dto.getConNum(),
                    dto.getUserId(),
                    dto.getEmail()
                };
                tableModel.addRow(rowData);  // <-- Correct way
            }

            // Optionally select the first row
            if (tableModel.getRowCount() > 0) {
                tblCustomer.setRowSelectionInterval(0, 0);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error loading customer data:\n" + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerDeleteBtn;
    private javax.swing.JButton CustomerSaveBtn;
    private javax.swing.JButton CustomerUpdateBtn;
    private javax.swing.JComboBox<String> cmbUserId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtConNum;
    private javax.swing.JTextField txtCusId;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
