package ControllerForm;

import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class DashboardForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());

    /**
     * Creates new form DashboardForm
     */
    public DashboardForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        customerBtn = new javax.swing.JButton();
        employeeBtn = new javax.swing.JButton();
        placeOrderBtn = new javax.swing.JButton();
        orderDetailsBtn = new javax.swing.JButton();
        itemBtn = new javax.swing.JButton();
        ingredientsBtn = new javax.swing.JButton();
        itemDetailsBtn = new javax.swing.JButton();
        suppliersBtn = new javax.swing.JButton();
        ingredientDetailsBtn = new javax.swing.JButton();
        existBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dashboard Form");

        customerBtn.setText("Customer");
        customerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBtnActionPerformed(evt);
            }
        });

        employeeBtn.setText("Employee");
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });

        placeOrderBtn.setText("Place Order");
        placeOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeOrderBtnActionPerformed(evt);
            }
        });

        orderDetailsBtn.setText("Order Details");
        orderDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDetailsBtnActionPerformed(evt);
            }
        });

        itemBtn.setText("Item");
        itemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBtnActionPerformed(evt);
            }
        });

        ingredientsBtn.setText("Ingredients ");
        ingredientsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientsBtnActionPerformed(evt);
            }
        });

        itemDetailsBtn.setText("Item Details");
        itemDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDetailsBtnActionPerformed(evt);
            }
        });

        suppliersBtn.setText("Suppliers");
        suppliersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersBtnActionPerformed(evt);
            }
        });

        ingredientDetailsBtn.setText("Ingredint Details");
        ingredientDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientDetailsBtnActionPerformed(evt);
            }
        });

        existBtn.setText("Exist");
        existBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(existBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(663, 663, 663))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(placeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(orderDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ingredientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(itemDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ingredientDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(suppliersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(674, 1205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(customerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(employeeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(placeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(itemDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingredientsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(suppliersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ingredientDetailsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(existBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingredientsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientsBtnActionPerformed
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(() -> {
        IngredientForm ingredientForm = new IngredientForm();
        ingredientForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        ingredientForm.setVisible(true);
    });
    }//GEN-LAST:event_ingredientsBtnActionPerformed

    private void customerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBtnActionPerformed
        // TODO add your handling code here:
        
        java.awt.EventQueue.invokeLater(() -> {
        CustomerForm customerForm = new CustomerForm();
        customerForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        customerForm.setVisible(true);
    });
    }//GEN-LAST:event_customerBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
        EmployeeForm employeeForm = new EmployeeForm();
        employeeForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        employeeForm.setVisible(true);
    });
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void placeOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeOrderBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
        OrderForm orderForm = null;
            try {
                orderForm = new OrderForm();
            } catch (SQLException ex) {
                System.getLogger(DashboardForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        orderForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        orderForm.setVisible(true);
    });
    }//GEN-LAST:event_placeOrderBtnActionPerformed

    private void orderDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDetailsBtnActionPerformed
        // TODO add your handling code here:
          java.awt.EventQueue.invokeLater(() -> {
        OrderDetailsForm orderDetailsForm = new OrderDetailsForm();
        orderDetailsForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        orderDetailsForm.setVisible(true);
    });
    }//GEN-LAST:event_orderDetailsBtnActionPerformed

    private void itemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
        ItemForm itemForm = new ItemForm();
        itemForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        itemForm.setVisible(true);
    });
    }//GEN-LAST:event_itemBtnActionPerformed

    private void itemDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDetailsBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
        ItemDetailsForm itemDetailsForm = null;
            try {
                itemDetailsForm = new ItemDetailsForm();
            } catch (SQLException ex) {
                System.getLogger(DashboardForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        itemDetailsForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        itemDetailsForm.setVisible(true);
    });
    }//GEN-LAST:event_itemDetailsBtnActionPerformed

    private void suppliersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
        SupplierForm supplierForm = new SupplierForm();
        supplierForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        supplierForm.setVisible(true);
    });
    }//GEN-LAST:event_suppliersBtnActionPerformed

    private void ingredientDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientDetailsBtnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(() -> {
        IngredientDetailsForm supplierDetailsForm = null;
            try {
                supplierDetailsForm = new IngredientDetailsForm();
            } catch (SQLException ex) {
                System.getLogger(DashboardForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        supplierDetailsForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        supplierDetailsForm.setVisible(true);
    });
    }//GEN-LAST:event_ingredientDetailsBtnActionPerformed

    private void existBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_existBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerBtn;
    private javax.swing.JButton employeeBtn;
    private javax.swing.JButton existBtn;
    private javax.swing.JButton ingredientDetailsBtn;
    private javax.swing.JButton ingredientsBtn;
    private javax.swing.JButton itemBtn;
    private javax.swing.JButton itemDetailsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderDetailsBtn;
    private javax.swing.JButton placeOrderBtn;
    private javax.swing.JButton suppliersBtn;
    // End of variables declaration//GEN-END:variables
}
