package ControllerForm;

import Dto.IngredientsDto;
import Dto.ItemDetailsDto;
import Dto.ItemDto;
import Model.IngredientsModel;
import Model.ItemDetailsModel;
import Model.ItemModel;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class ItemDetailsForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ItemDetailsForm.class.getName());

    /**
     * Creates new form ItemDetailsForm
     */
    public ItemDetailsForm() throws SQLException {
        initComponents();
        populateIngredientComboBox();
        populateItemComboBox();
        loadAllItemIngredient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtIngName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SaveBtnOnAction = new javax.swing.JButton();
        txtItemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemDetails = new javax.swing.JTable();
        cmbIngredientId = new javax.swing.JComboBox<>();
        cmbItemId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Item Details Form");

        jLabel5.setText("Ingredient Name");

        SaveBtnOnAction.setText("Save");
        SaveBtnOnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnOnActionActionPerformed(evt);
            }
        });

        jLabel4.setText("Ingredient ID");

        jLabel1.setText(" Item ID");

        jLabel2.setText("Item Name");

        tblItemDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " Item ID", "Item Name", "Ingredient ID", "Ingredient Name"
            }
        ));
        jScrollPane1.setViewportView(tblItemDetails);

        cmbIngredientId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbIngredientId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIngredientIdActionPerformed(evt);
            }
        });

        cmbItemId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbItemIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbIngredientId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SaveBtnOnAction)
                            .addGap(277, 277, 277))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIngName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbItemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbIngredientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIngName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(133, 133, 133)
                        .addComponent(SaveBtnOnAction))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(575, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbIngredientIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIngredientIdActionPerformed
        // TODO add your handling code here:
        IngredientsModel model = new IngredientsModel();
        String id = cmbIngredientId.getSelectedItem().toString();
        IngredientsDto ingDto = null;
        try {
            ingDto = model.search(id);
        } catch (SQLException ex) {
            System.getLogger(CustomerUpdateForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        txtIngName.setText(ingDto.getName());

    }

    public void populateIngredientComboBox() throws SQLException {

        List<String> dataFromDB = IngredientsModel.getCmbIngredientsId();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String id : dataFromDB) {
            model.addElement(id);
        }
        cmbIngredientId.setModel(model);
    }//GEN-LAST:event_cmbIngredientIdActionPerformed

    private void cmbItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemIdActionPerformed
        // TODO add your handling code here:
        ItemModel model = new ItemModel();
        String itemId = cmbItemId.getSelectedItem().toString();
        ItemDto itemDto = null;
        try {
            itemDto = model.search(itemId);
        } catch (SQLException ex) {
            System.getLogger(ItemUpdateForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        //CustomerDto cusDto = CustomerModel.search(cusId);
        txtItemName.setText(itemDto.getName());

    }//GEN-LAST:event_cmbItemIdActionPerformed

    public void populateItemComboBox() throws SQLException {

        List<String> dataFromDB = ItemModel.getCmbItemId();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String id : dataFromDB) {
            model.addElement(id);
        }
        cmbItemId.setModel(model);
    }


    private void SaveBtnOnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnOnActionActionPerformed
        // TODO add your handling code here:
        ItemDetailsModel model = new ItemDetailsModel();
        String itemId = cmbItemId.getSelectedItem().toString();
        String itemName = txtItemName.getText();
        String ingId = cmbIngredientId.getSelectedItem().toString();
        String ingName = txtIngName.getText();

        var dto = new ItemDetailsDto(itemId, ingId);

        boolean flag = false;
        try {
            flag = model.save(dto);
        } catch (SQLException ex) {
            System.getLogger(CustomerForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        if (flag) {
            JOptionPane.showMessageDialog(this,
                    "Item saved successfully! ",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Failed to save Item.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_SaveBtnOnActionActionPerformed

    private void clearFields() {

        txtItemName.setText("");
        txtIngName.setText("");

    }

    public void loadAllItemIngredient() {
        var model = new ItemDetailsModel();

        try {
            List<ItemDetailsDto> dtoList = model.getAll();
            DefaultTableModel tableModel = (DefaultTableModel) tblItemDetails.getModel();
            tableModel.setRowCount(0);

            // Add rows to the table
            for (ItemDetailsDto dto : dtoList) {
                Object[] rowData = {
                    dto.getItemId(),
                    dto.getItemName(),
                    dto.getIngId(),
                    dto.getIngName()

                };
                tableModel.addRow(rowData);  // <-- Correct way
            }

            // Optionally select the first row
            if (tableModel.getRowCount() > 0) {
                tblItemDetails.setRowSelectionInterval(0, 0);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error loading itemDetails data:\n" + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ItemDetailsForm().setVisible(true);
            } catch (SQLException ex) {
                System.getLogger(ItemDetailsForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtnOnAction;
    private javax.swing.JComboBox<String> cmbIngredientId;
    private javax.swing.JComboBox<String> cmbItemId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItemDetails;
    private javax.swing.JTextField txtIngName;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables
}
